POST http://localhost:6969/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFua3VyQGthbGl0YS5jb20iLCJleHAiOjE3MzUzNjE4NTgsInVzZXJJZCI6MX0.FsSVjTCIgUpTzD92fDibyfAYfQCh1OWC-DH8m9Rs1pg

{
    "name": "Hitler",
    "description": "A Social Worker",
    "location": "Germany",
    "dateTime": "2025-01-01T12:40:00.000Z"
}