POST http://localhost:6969/events
content-type: application/json

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T12:40:00.000Z"
}