DELETE http://localhost:6969/events/
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFua3VyMkBrYWxpdGEuY29tIiwiZXhwIjoxNzM1MzU3NDMwLCJ1c2VySWQiOjJ9.BBt-20TUJDuYzjKuH1oFfIPDl5DcuhwRsQZ9wnLKx5A
