DELETE http://localhost:6969/events/3
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFua3VyQGthbGl0YS5jb20iLCJleHAiOjE3MzUzNjAxMTMsInVzZXJJZCI6MX0.GtKBpdH_R0LhiNr9EMny3Vwh45hiApyfr1J0TfCSpGI
